# Generated by Django 3.0.3 on 2021-02-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_item_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['created'], 'verbose_name': 'Producto'},
        ),
        migrations.AddField(
            model_name='order',
            name='global_price',
            field=models.FloatField(default=0),
        ),
    ]
