# Generated by Django 3.0.3 on 2021-02-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210213_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adress',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
