# Generated by Django 3.0.3 on 2021-02-14 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20210214_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='one_click_purchasing',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_customer_id',
        ),
    ]
